### ISSUE TITLE
Problem on FIREFOX

### ISSUE THREAD

**Issue by iLenElFuerte** [blivesta/rippler#3]
Please try this code in Chrome (works fine) but does not work in Firefox onlick event (alert) and this happens only when the class 'rippler' is added

```html
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="content-type" content="text/html" />
	<meta name="author" content="lenin" />

	<title>Sin título 1</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    
      <link rel="stylesheet" href="http://git.blivesta.com/rippler/css/rippler.css">
      <script src="http://git.blivesta.com/rippler/js/jquery.rippler.js"></script>
</head>

<body>

<a href="#" class="miubtton rippler rippler-inverse" style="background: silver;color:#fff;padding: 5px 15px;">click</a>
<script>
$(document).ready(function() {
  $(".rippler").rippler();
  
  
  $(".miubtton").on("click",function(){
    alert("aaa");
  });
});
</script>
</body>
</html>
```

**Comment by neoranga55** [comment]
I also experience this problem on Firefox, a pity for an otherwise nice plugin.

**Comment by RedEars** [comment]
Same problem here. Need a fix ASAP

**Comment by RedEars** [comment]
As this issue is open a long time I decided to make a quick fix by myself:
Add this right before "_return _this" in the "elementRemove" function.  (Normally it should be between line 116 and 117)

```javascript
if(typeof _this['href'] != 'undefined'){
	window.location.href = _this.href;
}
```

**Comment by nr007** [comment]
Hey, try to set effectSize to 1. Firefox process click only on this circle which appears when you click on element and therefore click event does not come down to wanted element ("a" in your example).

**Comment by blivesta** [comment]
5c14f40
